FROM python:3.9-slim


WORKDIR /app

# install dependency: ab, docker, CLI, Java, wrk
RUN apt-get update && apt-get install -y \
    docker.io\
    docker-compose\
    apache2-utils \
    r-base \
    libssl-dev \
    libffi-dev \
    libxml2-dev \
    curl

ENV R_HOME=/usr/lib/R
ENV RPY2_CFFI_MODE=ABI

# Install Java separately
RUN apt-get update && \
    apt-get install -y wget gnupg && \
    wget -O /tmp/openjdk.tar.gz https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.18+10/OpenJDK11U-jre_x64_linux_hotspot_11.0.18_10.tar.gz && \
    mkdir -p /opt/java/openjdk && \
    tar -xf /tmp/openjdk.tar.gz -C /opt/java/openjdk --strip-components=1 && \
    rm /tmp/openjdk.tar.gz

RUN apt-get update && apt-get install -y wrk

# Set JAVA_HOME environment variable for Java 11
ENV JAVA_HOME /opt/java/openjdk
ENV PATH $JAVA_HOME/bin:$PATH

# Install Python requirements.txt
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy the code to docker
COPY . /app/

EXPOSE 8000

# default startup script(auto_runner)
# CMD ["python3", "auto_runner.py"]
